services:
  resido-server:
    container_name: resido-server
    restart: always
    image: node:20.20.2
    ports:
      - 3019:3006
    volumes:
      - ./:/usr/src/resido-server
    working_dir: /usr/src/resido-server

    networks:
      - resido-server_network

    command: bash -c "npm install && npm run build && npm run start:prod"

  resido-batch:
    container_name: resido-batch
    restart: unless-stopped
    image: node:20.20.2
    volumes:
      - ./:/usr/src/resido-batch
    working_dir: /usr/src/resido-batch
    networks:
      - resido-server_network

    command: bash -c "npm install && npm run build && npm run start:agenda"

networks:
  resido-server_network:
    driver: bridge
