export enum AgentNotificationType {
  AGENT_APPILICATION_SUBMITED = "AGENT_APPILICATION_SUBMITED",
  AGENT_APPLICATION_APPROVED = "AGENT_APPLICATION_APPROVED",
  AGENT_APPLICATION_REJECTED = "AGENT_APPLICATION_REJECTED",
  AGENT_APPILICATION_REJECTED = "AGENT_APPILICATION_REJECTED",
  AGENT_APPILICATION_REQUIRED = "AGENT_APPILICATION_REQUIRED",
  AGENT_APPLICATION_CONFIRMED = "AGENT_APPLICATION_CONFIRMED",
}

export enum AgentNotificationEntityType {
  AGENT_APPLICATION = "AGENT_APPLICATION",
  AGENT = "AGENT",
}
